### ISSUE TITLE
강의 정보 수정페이지에서 카테고리 선택시 나머지 컴포넌트도 리렌더링 되는 문제

### ISSUE THREAD

**Issue by TaehwanGo** [Ark-inflearn/inflearn-clone-front#83]
카테고리 id state를 props로 전달해서 이렇게 선택된 상태를 구현할 수도 있군요 :)
근데 아직 자세히 확인해보지는 못해서 정확하지는 않지만 개인적인 생각으로는 setIsSelected가 CourseCommonButton 컴포넌트가 아닌 course_info에서 state 변경이 발생해서 그런건지 카테고리 선택할 때 전체 화면에서 리렌더링이 발생하는 것 같아요.
![course_info_리렌더링](https://user-images.githubusercontent.com/8364940/135711256-c848df9e-3ca6-46d3-9eca-e1d94d4a44f7.gif)
혹시 course_info의 CourseCommonButton 컴포넌트 props에 setSelectedId를 전달하지 않고 구현할 수 있을까요?

_Originally posted by @hyoni0817 in https://github.com/Ark-inflearn/inflearn-clone-front/pull/80#discussion_r720657302_

**Comment by TaehwanGo** [comment]
선택될 때 마다 전체가 re-rendering 되는 문제
useState가 아닌 useRef로 테스트해보기

**Comment by TaehwanGo** [comment]
@hyoni0817 

![녹화_2021_10_02_20_29_56_734](https://user-images.githubusercontent.com/58352248/135714239-17e0f9ea-f3c9-4a00-b311-6c803a1e9e6e.gif)

useRef로 테스트를 해본 결과입니다.
제 결론은 안된다입니다.
useRef를 사용할 경우엔 전체가 re-rendering 되는 문제는 없어지지만
카테고리 버튼에서 다른 하나를 선택하면 기존에 선택된 것은 선택해제가 되어야 하는 기능이 동작하지 않았습니다.
이 부분을 해결하려면 추가적으로 useEffect를 사용해서 useRef값이 바뀔 때 마다 실행시켜서 전체를 검사하게 해서
버튼 부분만 리렌더링 되게 할 순 있겠지만
이게 useState를 사용하는 것에 비해 더 빠르다는 확신이 없고 코드도 복잡해지기 때문에 useState를 사용하는 것이 나은 것 같습니다.
더 좋은 의견있으면 언제나 피드백은 환영입니다. 🙂

**Comment by hyoni0817** [comment]
아예 map 코드까지 포함시켜서 컴포넌트 분리하면 어떨까하는 생각이 들어요. 
저도 CourseCommonButton 안에서만 구현해보려하니 올려주신 gif와 동일하게 카테고리를 선택했을 때, 선택한 카테고리 부분만 리렌링 되니까 다른 컴포넌트에 같이 변화를 일으키는게 말씀해주신 것 처럼 코드가 복잡해질 것 같네요ㅠㅠ
카테고리 부분만 전체 리렌더링 하는게 필요한 것 같아서 일단 한 번 따로 다시 분리 시켜보고 코멘트 다시 달겠습니다 :)

**Comment by TaehwanGo** [comment]
@hyoni0817 
그러면 useState가 아닌 redux store의 state를 이용해서 
저장 후 다음이동 버튼을 누를 때 취합한다면 가능할 것 같네요
저는 근데 리덕스가 번거로워서 웬만하면 붙어있는 컴포넌트끼린 잘 사용안하게 되는것 같아요 😅

**Comment by hyoni0817** [comment]
@TaehwanGo 
리덕스 대신에 다른 방법으로 구현할 코드를 생각해보다가 위에 useRef 사용하신 것을 아이디어로 삼아서 구현해보았습니다 :)
저장 후 다음이동 때도 카테고리 값이 잘 넘어가요 😃 
제가 구현한 방식은
1. map 함수를 포함해서 CourseCommonButton을 분리시킵니다.
2. CourseCommonButton(자식 컴포넌트)의 선택한 카테고리 state값을 props를 통해 부모 컴포넌트로 전달해요. 
3. 이 때 props는 함수로 되어있는데, 부모 컴포넌트에서 이 함수 안에 전달 받은 값을 useRef.current 배열에 저장시켜요
    useRef.current라고 했지만 상단에 const category = useRef(); 로 선언해줘서 사실은 category.current 입니다.
4. 그리고 저장한 값을 onClickSaveButton 안에 있는 data 객체에 같이 전달해줍니다.
    ```
    const data = {
      whatYouCanLearnList,
      expectedStudentsList,
      requiredKnowledgeList,
      selectedCategoryId: category.current[0],
      selectedLevelId,
    };
    ``
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/8364940/135728784-58be1f2f-a928-4f42-afa5-5fdf2d073359.gif)
화질이 안좋아서 잘 안보이는데 다음 이동 버튼 후 콘솔창에 빨간 글씨로 보이는게 카테고리 아이디 값이에요 :)
사실 좀 추상적으로 설명드린 것 같아서 소스 코드도 함께 보여드리고 싶은데 이것저것 건드리면서해서 정리가 안돼 오늘 미팅 끝나고 정리해서 추가하겠습니다.

이게 맞는 방식인지는 모르겠으나 일단 그냥 공부삼아 한 번 구현해봤습니다😂

**Comment by MinwooJJ** [comment]
배열에 [0, 1, 0, 0] 뭐 이런식으로 해놓고 filter 같은 값으로 자식컴포넌트에서 받아온 값으로 업데이트 해주는건가요?

**Comment by TaehwanGo** [comment]
좋은 시도 인 것 같아요
저도 사실 배열같이 관리해주는 추가 코드를 작성하는게 귀찮아서 안하려고 했었는데
나현님이 구현하신 것을 잘 정리해서 PR로 올려주시면 그걸 저희 main에 반영해도 좋을 것 같습니다 🙂

**Comment by TaehwanGo** [comment]
혹시 참고 하시라고 제가 어제 useRef로 테스트했던 코드 올렸습니다.

https://github.com/Ark-inflearn/inflearn-clone-front/commit/8fd361832788582185e0d99b68bf5063f311f447
https://github.com/Ark-inflearn/inflearn-clone-front/blob/category/rerenderingTest/issue83/src/pages/course/%5Bid%5D/edit/course_info.tsx

**Comment by hyoni0817** [comment]
@MinwooJJ 
아 토니님의 기존 소스 코드에서 선택된 아이디 값이 바뀔 때마다 useEffect를 통해 리렌더링 되는 코드를 사용해서 자식 컴포넌트 내에서만 업데이트가 되고, 부모 컴포넌트는 그냥 카테고리ID 값만 받아오고 업데이트에는 관여하지 않아요 :)

**Comment by hyoni0817** [comment]
@TaehwanGo 
나중에 그럼 정리해서 PR에 올리겠습니다 :)
올려주신 테스트 코드도 감사합니다👍  정리할 때 참고해서 같이 보겠습니다😊

**Comment by MinwooJJ** [comment]
자식 컴포넌트에서만 처리를 하나보네요. 나중에 코드를 봐야 확실하게 이해가 될듯하네요 제 머리는..ㅎㅎ :)

**Comment by hyoni0817** [comment]
@MinwooJJ 
사실 저도 쓰면서 코드 없이 대략적인 진행만 설명해놔서 보시는 입장에서는 이해가 잘 안되실 수 있을 것 같다는 생각을 했어요😅 
나중에 올릴 때는 코드랑 같이 좀 더 자세히 적어두겠습니다😃

**Comment by TaehwanGo** [comment]
#87
